core/urls.py
from django.urls import path
from .views import (
    HomeView, 
    ItemDetailView,
    CheckoutView,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    )
app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='item_list'),
    path('check-out/', CheckoutView.as_view(), name='check_out'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('order-summary/', OrderSummaryView.as_view(), name='order_summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('add-coupon/', AddCouponView.as_view, name='add_coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove_single_item_from_cart'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
# Create your models here.
CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport Wear'),
    ('OW', 'Outwear'),
)
LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secundary'),
    ('D', 'danger'),
)
class Item(models.Model):
    title = models.CharField(max_length=120)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    description = models.TextField()
    slug = models.SlugField()
    image = models.ImageField()

    class Meta:
        ordering = ('id',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})
    
    def get_add_to_cart_url(self):
        return reverse("core:add_to_cart", kwargs={'slug': self.slug})
    
    def get_remove_from_cart_url(self):
        return reverse("core:remove_from_cart", kwargs={'slug': self.slug})
    

class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_price(self):
        if self.item.discount_price:
            return self.item.discount_price
        else:
            return self.item.price

    def get_item_total_price(self):
        return self.quantity * self.item.price

    def get_item_total_discount_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_item_total_price() - self.get_item_total_discount_price()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_item_total_discount_price()
        else:
            return self.get_item_total_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateField(auto_now_add=True)
    oredered_date = models.DateField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon =  models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=150)
    apartment_address = models.CharField(max_length=150)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=150)

    def __str__(self):
        return self.user.username

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>E-commerce | {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  {% include 'components/main-navbar.html' %}
  {% if messages %}
  <div class="mt-5 pt-4">
    {% for message in messages %}
      <div class="alert alert-{% if message.tags == 'error' %}danger{%else%}{{message.tags}}{% endif %} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  </div>
  {% endif %}
  
  <!--Main layout-->     
    {% block content %}      
    {% endblock content %}
  <!--Main layout-->
  {% block extra_body %}
  {% endblock %}
  <!--Footer-->
    {% include 'components/footer.html'%}
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>

</html>

templates/checkout-page.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}
Checkout
{% endblock head_title %}
{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4"> 
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">
            <form class="card-body" method='POST'>
              {% csrf_token %}
              {{form|crispy}}
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
            </form>
            <!--Card content-->

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">
        {% include 'components/cart_summary.html' %}

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

templates/home-page.html
{% extends "base.html" %}
{% block head_title %}
Home
{% endblock head_title %}

{% block content %}
<main>
  <div class="container mt-5 pt-2">
      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->
      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for item in object_list %}
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4">

              <!--Card-->
              <div class="card">

                <!--Card image-->
                <div class="view overlay">
                  {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" alt=""> {% endcomment %}
                  <img src="{{item.image.url}}" class="card-img-top">
                    
                  <a href="{{item.get_absolute_url}}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
                <!--Card image-->

                <!--Card content-->
                <div class="card-body text-center">
                  <!--Category & Title-->
                  <a href="" class="grey-text">
                    <h5>{{item.get_category_display}}</h5>
                  </a>
                  <h5>
                    <strong>
                      <a href="{{item.get_absolute_url}}" class="dark-grey-text">{{item.title}}
                        <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                      </a>
                    </strong>
                  </h5>

                  <h4 class="font-weight-bold blue-text">
                    <strong>
                    {% if item.discount_price %}
                      {{item.discount_price}}$
                    {% else %}
                      {{item.price}}$
                    {% endif %}
                    
                    </strong>
                  </h4>

                </div>
                <!--Card content-->

              </div>
              <!--Card-->

            </div>
            <!--Grid column-->
          {% endfor %}
        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->
      <!--Pagination-->
      {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            <!--Arrow left-->
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">Previous</span>
                </a>
              </li>
            {% endif %}

            <li class="page-item active">
              <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
                <span class="sr-only">(current)</span>
              </a>
            </li>
            
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">Next</span>
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
      {% endif %}
      <!--Pagination-->
  </div>
</main>
{% endblock content %}

templates/item_list.html
{% extends "base.html" %}

{% block content %}
    <h2>List of items</h2>
    {% for item in items %}
        {{item.title}}
    {% endfor %}
{% endblock content %}

templates/order_summary.html
{% extends 'base.html' %}
{% block head_title %}
Order Summary
{% endblock head_title %}

{% block content %}
    <main class="mt-5 pt-5">
        <div class="container">
            <div class="table-responsive">
                <h2>Order summary</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Item</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{order_item.item.title}}</td>
                            <td>
                            {% if order_item.item.discount_price %}
                                ${{order_item.item.discount_price}}                  
                            {% else %}
                                ${{order_item.item.price}}
                            {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'core:remove_single_item_from_cart' order_item.item.slug %}" class=""><i class="fas fa-minus mr-1"></i></a>                                                             
                                {{order_item.quantity}}
                                <a href="{% url 'core:add_to_cart' order_item.item.slug %}"><i class="fas fa-plus ml-1"></i></a>
                                
                            </td>
                            <td>
                            {% if order_item.item.discount_price %}
                                ${{order_item.get_item_total_discount_price}}
                                <span class="badge badge-primary">
                                (saving ${{order_item.get_amount_saved}}) 
                                </span>                
                            {% else %}
                                ${{order_item.get_item_total_price}}
                            {% endif %}
                            <a href="{% url 'core:remove_from_cart' order_item.item.slug %}" 
                                class="float-right"
                                style='color: red; font-size:20px'>
                                <i class="fas fa-trash"></i>
                            </a>   
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="5">Your cart is empty</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                            <a class="btn btn-default float-right ml-2" href="{% url 'core:item_list' %}">Continue Shopping</a>
                            </td>
                        </tr>  
                        {% endfor %}
                        {% if object.get_total %}
                        {% if object.coupon %}
                            <tr>
                                <td colspan="4"><b>Coupon:</b></td>
                                <td><b>-${{object.coupon.amount}}</b></td>
                            </tr>
                        {% endif %}
                            <tr>
                                <td colspan="4"><b> Order Total: </b></td>
                                <td><b>${{object.get_total}}</b></td>
                            </tr>
                            <tr>
                                <td colspan="5">
                                <a class="btn btn-default float-right ml-2" href="{% url 'core:item_list' %}">Continue Shopping</a>
                                <a class="btn btn-warning float-right" href="{% url 'core:check_out' %}">Proceed to checkout</a>
                                </td>
                            </tr>                 
                        {% endif %}
                    </tbody>
                </table>
            </div>
        
        </div>
    </main>
{% endblock content %}

templates/payment.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}
Payment
{% endblock head_title %}

{% block extra_head %}

<style>
    
body, html {
  height: 100%;
  background-color: #f7f8f9;
  color: #6b7c93;
}

*, label {
  font-family: "Helvetica Neue", Helvetica, sans-serif;
  font-size: 16px;
  font-variant: normal;
  padding: 0;
  margin: 0;
  -webkit-font-smoothing: antialiased;
}

button.stripe-button {
  border: none;
  border-radius: 4px;
  outline: none;
  text-decoration: none;
  color: #fff;
  background: #32325d;
  white-space: nowrap;
  display: inline-block;
  height: 40px;
  line-height: 40px;
  padding: 0 14px;
  box-shadow: 0 4px 6px rgba(50, 50, 93, .11), 0 1px 3px rgba(0, 0, 0, .08);
  border-radius: 4px;
  font-size: 15px;
  font-weight: 600;
  letter-spacing: 0.025em;
  text-decoration: none;
  -webkit-transition: all 150ms ease;
  transition: all 150ms ease;
  float: left;
  margin-left: 12px;
  margin-top: 28px;
}

button:hover {
  transform: translateY(-1px);
  box-shadow: 0 7px 14px rgba(50, 50, 93, .10), 0 3px 6px rgba(0, 0, 0, .08);
  background-color: #43458b;
}

form.stripe-form {
  padding: 30px;
  height: 120px;
}

label.stripe-label {
  font-weight: 500;
  font-size: 14px;
  display: block;
  margin-bottom: 8px;
}

#card-errors {
  height: 20px;
  padding: 4px 0;
  color: #fa755a;
}

div.stripe-form-row {
  width: 70%;
  float: left;
}

.token {
  color: #32325d;
  font-family: 'Source Code Pro', monospace;
  font-weight: 500;
}

.wrapper {
  width: 670px;
  margin: 0 auto;
  height: 100%;
}

#stripe-token-handler {
  position: absolute;
  top: 0;
  left: 25%;
  right: 25%;
  padding: 20px 30px;
  border-radius: 0 0 4px 4px;
  box-sizing: border-box;
  box-shadow: 0 50px 100px rgba(50, 50, 93, 0.1),
    0 15px 35px rgba(50, 50, 93, 0.15),
    0 5px 15px rgba(0, 0, 0, 0.1);
  -webkit-transition: all 500ms ease-in-out;
  transition: all 500ms ease-in-out;
  transform: translateY(0);
  opacity: 1;
  background-color: white;
}

#stripe-token-handler.is-hidden {
  opacity: 0;
  transform: translateY(-80px);
}

/**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}

</style>
{% endblock extra_head %}

{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4"> 
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Payment</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-12 mb-4">

          <!--Card-->
          <div class="card">
            <script src="https://js.stripe.com/v3/"></script>

            <form action="." method="post" id="payment-form" class="stripe-form">
              {% csrf_token %}
                <div class="stripe-form-row">
                    <label for="card-element" class="stripe-label">
                    Credit or debit card
                    </label>
                    <div id="card-element">
                    <!-- A Stripe Element will be inserted here. -->
                    </div>

                    <!-- Used to display form errors. -->
                    <div id="card-errors" role="alert"></div>
                </div>

                <button class="stripe-button">Submit Payment</button>
            </form>
            <!--Card content-->

          </div>
          <!--/.Card-->
          
            
        </div>
        <!--Grid column-->
        <!--Grid column-->
        {% comment %} SUMMARY {% endcomment %}
        {% include 'components/cart_summary.html' %}
        <!--Grid column-->
      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

<script>
    // Create a Stripe client.
    var stripe = Stripe('pk_test_51Hu8yEA1Ibmmqdn5WWEHqwGFLnA4EcVXp06DAN4T7ZjopI6cYtBGAEFfQKHDsMQLrMfhbLUN5IA7OtsQUrrb1mvk00naztW9aT');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
    base: {
        color: '#32325d',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
        color: '#aab7c4'
        }
    },
    invalid: {
        color: '#fa755a',
        iconColor: '#fa755a'
    }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');
    // Handle real-time validation errors from the card Element.
    card.on('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
        displayError.textContent = event.error.message;
    } else {
        displayError.textContent = '';
    }
    });

    // Handle form submission.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
        if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
        } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
        }
    });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    form.submit();
    }
</script>

{% endblock content %}

templates/product-page.html
{% extends "base.html" %}
{% block content %}
<!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{object.get_category_display}}</span>
              </a>
            </div>

            <p class="lead">
              
              {% if object.discount_price %}
                <span class="mr-1">
                  <del>${{object.price}}</del>
                </span>
                <span>${{object.discount_price}}</span>
              {% else %}
                <span>${{object.price}}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.description}}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{object.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{object.get_remove_from_cart_url}}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
              <del><i class="fas fa-shopping-cart ml-1"></i></del>
            </a>


          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}