core/urls.py
from django.urls import path
from .views import (
    HomeView, 
    ItemDetailView,
    CheckoutView,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    )
app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='item_list'),
    path('check-out/', CheckoutView.as_view(), name='check_out'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('order-summary/', OrderSummaryView.as_view(), name='order_summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('add-coupon/', AddCouponView.as_view, name='add_coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove_single_item_from_cart'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/components/cart_summary.html
<div class="col-md-12 mb-4">

    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{order_item.quantity}} x {{order_item.item.title}}</h6>
        <small class="text-muted">{{order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{order_item.get_final_price}}</span>
    </li>
    {% endfor %}
    {% if order.coupone %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{order.coupon.code}}</small>
        </div>
        <span class="text-success">-${{order.coupon.amount}}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{order.get_total}}</strong>
    </li>
    </ul>
    <!-- Cart -->
    <!-- Promo code -->
    {% if DISPLAY_COUPON_FORM %}
        <form class="card p-2" action="{% url 'core:add_coupon' %}" method='POST'>
            {% csrf_token %}
            <div class="input-group">
                {% comment %} <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2"> {% endcomment %}
                {{form_coupon.as_p}}
                <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                </div>
            </div>
        </form>

    {% endif %}
    <!-- Promo code -->

</div>

templates/components/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/components/main-navbar.html
{% load cart_template_tags %}
<!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'core:item_list' %}">
        <strong class="blue-text">E-commerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'core:item_list' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:check_out' %}" target="_blank">Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'core:order_summary' %}">
                <span class="badge red z-depth-1 mr-1"> {{request.user|cart_item_count}} </span>
                <i class="fas fa-shopping-cart"></i>
                <span class="clearfix d-none d-sm-inline-block"> Cart </span>
              </a>
            </li>       
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                <span class="clearfix d-none d-sm-inline-block"> Logout </span>
              </a>
            </li> 
          {% else %}
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                <span class="clearfix d-none d-sm-inline-block"> Login </span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                <span class="clearfix d-none d-sm-inline-block"> SignUp </span>
              </a>
            </li>
          {% endif %}          
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->